services:

  web:
    build: .

    depends_on:
      - db
      - redis

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

  db:
    image: postgres:16

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
    - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7

volumes:
  postgres_data: 

