# Generated by Django 6.0.1 on 2026-10-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_alter_message_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-latest_messages__created']},
        ),
    ]
