# Generated by Django 6.0.1 on 2026-10-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
