# Generated by Django 6.0.1 on 2026-10-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_alter_room_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='latest_messages',
            new_name='latest_message',
        ),
    ]
