# Generated by Django 6.0.1 on 2026-06-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('product', 'attribute')},
        ),
    ]
