# Generated by Django 6.0.1 on 2026-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attr_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('select', 'Выбор из списка')], default='text', max_length=10),
        ),
    ]
