# Generated by Django 6.0.1 on 2026-07-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_attribute_attr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attr_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число')], default='text', max_length=10),
        ),
    ]
