# Generated by Django 6.0.1 on 2026-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_attribute_attr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
